services:
  yaci-address-balance-monitor:
    build:
      context: .
      target: production
    image: cardanofoundation/yaci-address-balance-monitor:latest
    env_file:
      - .env
    ports:
      - ${YACI_STORE_PORT:-8080}:8080
    volumes:
      - $PWD/data/h2-data:/data
      - $PWD/data/node-exporter:/data/node-exporter
      - $PWD/config:/app/config/
      - $PWD/plugins:/app/plugins/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
